apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
  namespace: taskmanager
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: taskmanager
  DB_PASSWORD: root
  SESSION_SECRET: taskmanager123