apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
  namespace: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-app
  template:
    metadata:
      labels:
        app: taskmanager-app
    spec:
      containers:
        - name: taskmanager-app
          image: sweshsmarth/task-manager-app:latest  # ✅ FIXED
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: taskmanager-config
            - secretRef:
                name: taskmanager-secret