# ══════════════════════════════════════════════════════
#   PERSISTENT VOLUME CLAIM — Fixed for Minikube/Windows
#   Uses storageClassName: standard (Minikube default)
#   No need to manually create PV — Minikube handles it
# ══════════════════════════════════════════════════════

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: taskmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard      # ← Minikube's built-in storage
  resources:
    requests:
      storage: 1Gi
